### ISSUE TITLE
Shared memory segments are not released upon drop

### ISSUE THREAD

**Issue by cannonpalms** [boustrophedon/pgtemp#13]
Hello! :wave: 

I believe that I've come across a bug where `pgtemp` will leak shared memory segments created by postgres & friends.

My use case is very straightforward: Create a new instance of Postgres for each benchmark test case.

This worked flawlessly out of the box until several days later. After several days of working on these benchmarks, I had probably created thousands of Postgres instances with `pgtemp`. Eventually, I hit a wall, and could not create more. 

## Problem statement

**`pgtemp` leaks shared memory segments upon the shutdown of a postgresql instance.**

I am now unable to spin up new postgres instances, instead receiving the error below:

### Error message
```
thread 'main' panicked at /home/cannon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pgtemp-0.4.0/src/run_db.rs:72:9:
initdb failed! stdout: The files belonging to this database system will be owned by user "cannon".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

creating directory /tmp/pgtemp-NInrLh/pg_data_dir ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 20
selecting default shared_buffers ... 400kB
selecting default time zone ... America/New_York
creating configuration files ... ok
running bootstrap script ...

stderr: 2024-09-23 17:22:00.490 EDT [1010753] FATAL:  could not create shared memory segment: No space left on device
2024-09-23 17:22:00.490 EDT [1010753] DETAIL:  Failed system call was shmget(key=5140062, size=56, 03600).
2024-09-23 17:22:00.490 EDT [1010753] HINT:  This error does *not* mean that you have run out of disk space.  It occurs either if all available shared memory IDs have been taken, in which case you need to raise the SHMMNI parameter in your kernel, or because the system's overall limit for shared memory has been reached.
        The PostgreSQL documentation contains more information about shared memory configuration.
child process exited with exit code 1
initdb: removing data directory "/tmp/pgtemp-NInrLh/pg_data_dir"
```

This is quite a nice error message (thank you for piping output back through stdout/stderr, @boustrophedon!). The problem is thus: `initdb`/`postgresql`  wants to create a[t least one] shared memory segment at start-up. Specifically, it's looking to acquire 56 bytes ("Failed system call was `shmget(key=5140062, size=56, 036000)`.) Either the maximum amount of shared memory is being exceeded by 56 bytes (unlikely considering a limit of 16 EB), OR the maximum number of shared memory pages have been allocated (quite likely, considering a limit of 4096 pages!)

### Additional context

The following may be Linux-specific. I haven't tried it on MacOS or Windows.

We can inspect our shared memory using `ipcs`. 

```console
$ ipcs --shmems --human
------ Shared Memory Segments --------
key        shmid      owner      perms      bytes      nattch     status
<shm key>  <rand>     <user>     600        56B        0
...(line above with 56 bytes repeats thousands of times)...
```

In my case, there are **`4095`** shared memory segments of 56 bytes (plus 1 segment from another process), and by default my machine allows a maximum number of segments of **`4096`**. 

```console
$ ipcs --shmems --limits --human

------ Shared Memory Limits --------
max number of segments = 4096
max seg size = 16E
max total shared memory = 16E
min seg size = 1B
```

**Conclusion: shared memory from Postgresql may leak beyond the default `drop()` impl.**

I manually cleaned up these dangling shared memory segments:

```shell
#!/bin/sh -
ipcs -m --human | grep '56B' | awk '{print $2}' | xargs -n 1 -t ipcrm -m
```

#### Reproducer
```rust
use sqlx::Connection;

#[tokio::main]
async fn main() {
    let db = create_db();
    let mut conn = sqlx::postgres::PgConnection::connect(&db.connection_uri())
        .await
        .expect("Failed to connect to Postgres");

    conn.ping().await.expect("Failed to ping Postgres");

    println!("Successfully pinged Postgres");
}

fn create_db() -> pgtemp::PgTempDB {
    pgtemp::PgTempDBBuilder::new().start()
}
```

We can run a `watch` in another session:
```console
$ watch 'ipcs -m --human | grep 56B'
Every 2.0s: ipcs -m --human --time                                                                                           HOST: Mon Sep 23 19:02:40 2024


------ Shared Memory Attach/Detach/Change Times --------
shmid      owner      attached             detached             changed
0          root       Sep 21 10:51:26      Not set              Sep 21 10:51:26
2850822    USER       Sep 23 18:55:08      Sep 23 18:55:08      Sep 23 18:55:08
2850827    USER       Sep 23 18:55:12      Sep 23 18:55:12      Sep 23 18:55:11
2850833    USER       Sep 23 19:02:10      Sep 23 19:02:10      Sep 23 19:02:10
.....
```

The list will continue to grow each time you run the reproducer. It will never shrink.

## Root cause

I'm no expert, but I can share what I've found online thus far.

- "When you kill the postmaster process forcibly, it doesn't
release the shared memory segments that it had allocated."[^1]

[^1]: https://postgrespro.com/list/thread-id/1955507

-----------

_P.S. I've been using this library for some benchmarking and it's been very enjoyable! Thank you for such a simple yet brilliantly useful crate._

**Comment by boustrophedon** [comment]
Hey, thanks for the very detailed bug report!

That mailing list thread is from 2004 but it seems very possible that it's still relevant.

Could you try using the graceful_shutdown branch I just pushed? Your Cargo.toml should look like

```
[dependencies]
[...]
pgtemp = { git = "https://github.com/boustrophedon/pgtemp.git", branch = "graceful_shutdown" }
```

You might have to delete your Cargo.lock file or run cargo clean to get it to pick up the branch.

**Comment by cannonpalms** [comment]
I can confirm that with cd51424 (tip of branch `graceful_shutdown`), dangling shared memory segments are no longer being created!

**Comment by boustrophedon** [comment]
Sounds good, I'll add a `force_shutdown` method and make the default behavior on drop graceful shutdown. Thanks again for the report!

**Comment by boustrophedon** [comment]
This actually was mentioned in the documentation: https://www.postgresql.org/docs/current/server-shutdown.html

I'm going to use SIGINT for fast shutdown, rather than smart shutdown, because it seems like there's probably a race condition/deadlock happening with async connection poolers if I just use graceful shutdown everywhere.

**Comment by boustrophedon** [comment]
I pushed 0.5.0 to crates.io. Could you test it one more time before I close this issue? Thanks!

**Comment by cannonpalms** [comment]
@boustrophedon Perhaps you're already aware of this / perhaps it was done intentionally to aid troubleshooting, but I'm seeing significant performance issues with cd51424. 

- _from_: 83 simple inserts/s 
- _to_: 0.4 simple inserts/s

It's worth noting that I do not include DB provisioning time in my benchmark, but it does impact the amount of time taken per benchmark iteration.

--------

Sure, I'll test `0.5.0` now.

**Comment by boustrophedon** [comment]
Are you measuring the time included to drop the database? It should take more time to drop with graceful vs SIGKILL, and it should take somewhat more but less than graceful with fast shutdown vs SIGKILL.

If your perf is still significantly impacted by the SIGINT/fast shutdown, we can try the immediate shutdown mode and only use SIGINT/fast shutdown with persist.

**Comment by cannonpalms** [comment]
Sorry, I still haven't tested 0.5.0. Had to fix some neovim config issues. I'll test it now.

I'm using criterion's `iter_custom` to avoid measuring the time it takes to drop the database, but when I said, "this seems slower," I was referring to the output from criterion about how many iterations it thinks it can do in X seconds. The latter probably does include drop time.

----------------

As an aside, how disgusting would it be to `ipcrm` the leaked shmem ourselves, and continue to enjoy the fast shutdown :stuck_out_tongue_winking_eye:. I'm mostly kidding.

I'll get back to you in a minute with more news.

**Comment by cannonpalms** [comment]
`0.5.0` shows significantly less impact on iterations/s than the `graceful_shutdown` branch did.

Let me write up a benchmark specifically for constructing & dropping, so that I can give you real data.

**Comment by cannonpalms** [comment]
Confirmed via benchmark that dropping now takes 4x time on my machine. Oh well, that's a fair price to pay for avoiding the shmem leak. I can rework things on my end to make dropping a rare event (more pgtempdb reuse!)

#### `0.5.0
```v
pgtemp/construct_and_drop:
                        time:   [5.7217 ms 5.9500 ms 6.1870 ms]
                        thrpt:  [161.63  elem/s 168.07  elem/s 174.77  elem/s]
```

**Comment by boustrophedon** [comment]
If you want to double check, you could fork pgtemp and change the SIGINT to SIGQUIT and see if it's any faster. If 0.5 is about as fast as 0.4 then I agree, we can close the issue.
